"""
PARSA REPORT LAYER (LAYER 6 - PHASE 3 HARDENED)
===============================================
Synthesizes verified Judge and Guardian results into presentation formats and Markdown reports.
Cannot create, modify, or project unverified scientific claims.
"""

from typing import List, Dict, Any, Optional
import time
from parsa_layers.contracts.models import (
    JudgeResult,
    GuardianFinding,
    ReportRecord,
    UnauthorizedLayerAccessViolation,
    compute_sha256
)
from parsa_layers.contracts.access_control import enforce_layer


class ReportEngine:
    """Presentation and Report Synthesis Engine."""

    def __init__(self, experiment_id: str, version: str = "3.0.0"):
        self.experiment_id = experiment_id
        self.version = version

    @enforce_layer("REPORT")
    def generate_report(
        self,
        title: str,
        judge_result: JudgeResult,
        guardian_findings: List[GuardianFinding],
        timestamp: Optional[float] = None
    ) -> ReportRecord:
        """Constructs an immutable ReportRecord from validated Judge and Guardian inputs."""
        now = timestamp if timestamp is not None else time.time()
        report_id = f"REP-{self.experiment_id}-{int(now)}"

        # Check if any Guardian finding has INVALID or FAIL
        has_critical = any(f.severity == "CRITICAL" and f.status in ("INVALID", "FAIL") for f in guardian_findings)
        guardian_status = "INVALIDATED_BY_GUARDIAN" if has_critical else "VERIFIED_BY_GUARDIAN"

        summary_text = (
            f"Experiment {self.experiment_id} evaluated with N={judge_result.sample_size} outcomes. "
            f"Win Rate: {judge_result.win_rate_pct}%. Classification: {judge_result.law_classification}. "
            f"Guardian Status: {guardian_status}."
        )

        verdict_summary = {
            "sample_size": judge_result.sample_size,
            "correct_count": judge_result.correct_count,
            "wrong_count": judge_result.wrong_count,
            "not_realized_count": judge_result.not_realized_count,
            "win_rate_pct": judge_result.win_rate_pct,
            "t_statistic": judge_result.t_statistic,
            "p_value": judge_result.p_value,
            "bonferroni_threshold": judge_result.bonferroni_threshold,
            "is_significant": judge_result.is_statistically_significant,
            "law_classification": judge_result.law_classification,
            "real_money_authorized": judge_result.real_money_authorized,
            "confidence_interval_95": list(judge_result.confidence_interval_95),
            "effect_size": judge_result.effect_size
        }

        return ReportRecord(
            report_id=report_id,
            timestamp=now,
            source="REPORT_ENGINE_V3",
            version=self.version,
            title=title,
            summary=summary_text,
            verdicts_summary=verdict_summary,
            guardian_status=guardian_status,
            parent_hash=judge_result.hash
        )

    @enforce_layer("REPORT")
    def render_markdown(self, report: ReportRecord) -> str:
        """Renders the report in clean Markdown."""
        vs = report.verdicts_summary
        ci = vs.get('confidence_interval_95', [0.0, 0.0])
        md = f"""# 📊 PARSA EXPERIMENTAL EVALUATION REPORT (PHASE 3 HARDENED)
**Report ID:** `{report.report_id}`  
**Title:** {report.title}  
**Timestamp:** {report.timestamp}  
**Guardian Verification Status:** `{report.guardian_status}`

---

### 1. Statistical Adjudication Summary
- **Sample Size ($N$):** {vs.get('sample_size')}
- **Correct Outcomes:** {vs.get('correct_count')}
- **Wrong Outcomes:** {vs.get('wrong_count')}
- **Not Realized / Neutral:** {vs.get('not_realized_count')}
- **Directional Win Rate:** {vs.get('win_rate_pct')}%
- **95% Wilson Confidence Interval:** [{ci[0]}%, {ci[1]}%]
- **Effect Size (Cohen's $h$):** {vs.get('effect_size')}
- **Statistical Test (z / t-statistic):** {vs.get('t_statistic')}
- **p-value:** {vs.get('p_value')}
- **Bonferroni Alpha Threshold:** {vs.get('bonferroni_threshold')}
- **Statistically Significant:** {vs.get('is_significant')}
- **Scientific Law Classification:** `{vs.get('law_classification')}`
- **Real-Money Trading Authorization:** `{vs.get('real_money_authorized')}`

---
*Generated by PARSA Layer 6 (REPORT) | Cryptographic Hash: `{report.hash}`*
"""
        return md
